version: "3.8"
services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mongodb://database:27017/mydatabase
    depends_on:
      - database
  frontend:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
