name: Deploy Node Application

on:
  push:
    branches:
      - mern-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t mohamedamaan319/aws-fullstackhenna .

      - name: Publish Image to docker hub
        run: docker push mohamedamaan319/aws-fullstackhenna:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull mohamedamaan319/aws-fullstackhenna:latest

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name nodejs-app-container -e MONGODB_PASSWORD='${{ secrets.MONGODB_PASSWORD }}' mohamedamaan319/aws-fullstackhenna:latest
